# Generated by Django 3.1.3 on 2021-01-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210108_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='article'),
        ),
    ]
